### PR TITLE
Release 1.5.1

### PR DESCRIPTION
**Pull request by techknowlogick**
As title

Blocked by: https://github.com/go-gitea/gitea/pull/4851

### CODE REVIEW

**Comment by appleboy** [comment]
@techknowlogick @lunny Just add pull request link. See https://github.com/go-gitea/blog/pull/73/commits/e4a17ef435098b2b69cfc706f0634da406ba1ff5

**Comment by lunny** [comment]
@appleboy OK. and don't merge until v1.5.1 tag and released.

**Comment by techknowlogick** [comment]
@appleboy thank you, this was helpful.

**Comment by techknowlogick** [comment]
make LG-TM work

**Pull request merged**
