### PR TITLE
First draft of a first blog post

### PR DESCRIPTION
**Pull request by strk**
This is an initial draft. I think something should be written
about the infrastructure (@tboerger maybe you can do that?).

And probably the invite for Unknwon should be more explicit.

Finally, the Hugo configuration and file format (links compltely
missing, for example) should be taken care of.

Let me know if you think it'll be easier for this branch to be
pushed on the official repository rather than in my branch to
help contributing changes until we're happy with it.

### CODE REVIEW

**Comment by tboerger** [comment]
I like the text!

**Comment by andreynering** [comment]
LGTM

**Comment by metalmatze** [comment]
The text is really solid! 
I'd only like add a section that covers the future plans of gitea. 
E.g. refactoring almost everything, write more tests etc. Something people can look forward to in the future! 😊👍

**Comment by strk** [comment]
@metalmatze yes I also think such a section should be added right before the invite, but maybe the plan should be expressed by the owners, for their year of competence. As long as this is in draft state we could merge this and ask owners to send a PR to add the road ahead section ?

**Comment by metalmatze** [comment]
LGTM

**Comment by jhasse** [comment]
Link at the bottom should be https instead of http, shouldn't it?

**Comment by strk** [comment]
https didn't work at the time of writing, now seem to be working.
it could be fixed next time someone wants to propose an addition (the road-ahead?)

**Comment by lunny** [comment]
Where is the blog posted? @tboerger It seems `https://blog.gitea.io` is empty.

**Comment by strk** [comment]
Being in draft is not visible unless a flag is passed to `hugo` to also build draft pages.
Additionally, I didn't add any link from main page as I'm hoping there's some magic that would do that automatically (and that some of you guys know about it :).

Once the page is built, it should be under `post/welcome-to-gitea` (at least I saw it there, locally).
Ideally, we'd have a date embedded in the url too, but again it takes someone who knows Hugo better than myself

**Pull request merged**
