### PR TITLE
remove sig file and add secret via `--skip-verify` flag

### PR DESCRIPTION
**Pull request by appleboy**
As title.

### CODE REVIEW

**Comment by lunny** [comment]
where is the `--skip-verify`?

**Comment by appleboy** [comment]
@lunny 

```sh
drone secret add  --skip-verify --image=appleboy/drone-discord   --event=pull_request   go-gitea/blog WEBHOOK_TOKEN xxxxxx
```

**Comment by lunny** [comment]
But I only see the sig file removed, not any other changes?

**Comment by appleboy** [comment]
yes, I only add discord secret which needs to update sig file but I remove sig file after add `--skip-verify`flag.

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
