### PR TITLE
Add blog post for 1.5.0

### PR DESCRIPTION
**Pull request by techknowlogick**
Date will need to be changed to the correct release date.

### CODE REVIEW

**Comment by sondr3** [comment]
Are you gonna expand on the features in this release akin to the blog post for 1.4? It was a big plus in my book to delve a bit deeper into the new and big features that came with that release instead of just listing the changelog and a small paragraph about this release.

**Comment by lunny** [comment]
I would like you include a public gpg key here for verify the downloads. I have uploaded that one #maintainers channel.

**Comment by techknowlogick** [comment]
@lunny Good Idea. I think we should put that on gitea.io website and link to it from this blog post. I've added a line about GPG updates.

@sondr3 good idea. I've just added some text to the blog post which expands on changes.

**Comment by lafriks** [comment]
It would be nice to add notice that we will be dropping integrated TiDB support in next release

**Comment by techknowlogick** [comment]
@lafirks that is in the blog post


On Wed, Jul 4, 2018, at 5:41 PM, Lauris BH wrote:
> It would be nice to add notice that we will be dropping integrated
> TiDB support in next release> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/go-gitea/blog/pull/64#issuecomment-402562985

**Comment by lafriks** [comment]
Oh, sorry you are right, missed that :)

**Comment by lafriks** [comment]
@thehowl could you add more detailed info with screenshots etc about new features?

**Comment by thehowl** [comment]
Hey - I'm quite overwhelmed with work as of lately and I kind of lost interest in Gitea (I should get around to ask to be moved to advisors :P) but I guess I can try to make time to sum up the changes and make a changelog like the previous one. I'll try to do it over the weekend.

**Comment by lunny** [comment]
@thehowl do you have time to do that?

**Comment by thehowl** [comment]
I'll get to it now

**Comment by techknowlogick** [comment]
@thehowl I gave you push access to my repo. Feel free to make changes directly to this PR.

**Comment by techknowlogick** [comment]
Closing as #72 exists now.

**Pull request closed without merging**
